site_name: Criteria
#theme: 'material'
theme: null
theme_dir: 'mkdocs-material/material/'
docs_dir: 'content'
site_dir: 'site'
pages:
- Welcome: index.md
- Usage: usage.md
- Criteria: criteria.md
- Team: team.md
